# Generated by Django 2.2.7 on 2020-08-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='category',
            field=models.TextField(default='work-experience'),
        ),
    ]
